# version: '3.8'

services:
  nextjs:
    image: school-management-system-nextjs-school2:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3002}:3002"
    env_file:
     - .env
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=https://${DOMAIN}
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - PORT=3002

    labels:
      - traefik.enable=true
      - traefik.http.routers.school2-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.school2-http.entrypoints=http
      - traefik.http.routers.school2-http.middlewares=https-redirect
      - traefik.http.routers.school2-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.school2-https.entrypoints=https
      - traefik.http.routers.school2-https.tls=true
      - traefik.http.routers.school2-https.tls.certresolver=le
      - traefik.http.routers.school2-https.service=school2-service
      - traefik.http.services.school2-service.loadbalancer.server.port=3002
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      # - web
      - traefik-public
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME:-postgres}
      - DB_HOST=${DB_HOST}
    volumes:
      - postgres-data-school2:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - ./backups:/app/backups
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - traefik-public
    command:
      - "postgres"
      - "-c"
      - "ssl=off"

volumes:
  postgres-data-school2:
    driver: local

networks:
  # web:
  #   external: true
  traefik-public:
    external: true
